services:
  algorithm_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3003:3003"
    volumes:
      - ./algorithm_navi:/app
      - algorithm_navi_node_modules:/app/node_modules
      - algorithm_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3003"

  system_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3004:3004"
    volumes:
      - ./system_navi:/app
      - system_navi_node_modules:/app/node_modules
      - system_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3004"

  ml_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3005:3005"
    volumes:
      - ./ml_navi:/app
      - ml_navi_node_modules:/app/node_modules
      - ml_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3005"

  theory_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3006:3006"
    volumes:
      - ./theory_navi:/app
      - theory_navi_node_modules:/app/node_modules
      - theory_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3006"

  network_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3007:3007"
    volumes:
      - ./network_navi:/app
      - network_navi_node_modules:/app/node_modules
      - network_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3007"

  db_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3008:3008"
    volumes:
      - ./db_navi:/app
      - db_navi_node_modules:/app/node_modules
      - db_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3008"

  language_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3009:3009"
    volumes:
      - ./language_navi:/app
      - language_navi_node_modules:/app/node_modules
      - language_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3009"

  software_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3010:3010"
    volumes:
      - ./software_navi:/app
      - software_navi_node_modules:/app/node_modules
      - software_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3010"

  cloud_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3011:3011"
    volumes:
      - ./cloud_navi:/app
      - cloud_navi_node_modules:/app/node_modules
      - cloud_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3011"

volumes:
  algorithm_navi_node_modules:
  algorithm_navi_docusaurus:
  system_navi_node_modules:
  system_navi_docusaurus:
  ml_navi_node_modules:
  ml_navi_docusaurus:
  theory_navi_node_modules:
  theory_navi_docusaurus:
  network_navi_node_modules:
  network_navi_docusaurus:
  db_navi_node_modules:
  db_navi_docusaurus:
  language_navi_node_modules:
  language_navi_docusaurus:
  software_navi_node_modules:
  software_navi_docusaurus:
  cloud_navi_node_modules:
  cloud_navi_docusaurus:
