services:
  programming_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3003:3003"
    volumes:
      - ./programming_navi:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3003"

  computer_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3004:3004"
    volumes:
      - ./computer_navi:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3004"

  security_navi:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3012:3012"
    volumes:
      - ./security_navi:/app
      - security_navi_node_modules:/app/node_modules
      - security_navi_docusaurus:/app/.docusaurus
    working_dir: /app
    command: sh -c "yarn install && yarn start --host 0.0.0.0 --port 3012"

volumes:
  security_navi_node_modules:
  security_navi_docusaurus:
