import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import * as fs from 'fs';
import * as path from 'path';

function buildSidebarCategories(dirName: string) {
  const dir = path.join(__dirname, 'docs', dirName);
  const subdirs = fs
    .readdirSync(dir)
    .filter(name => fs.statSync(path.join(dir, name)).isDirectory())
    .sort();

  return subdirs.map(subdir => ({
    type: 'category' as const,
    label: subdir.replace(/^\d+_/, ''),
    items: [{ type: 'autogenerated' as const, dirName: `${dirName}/${subdir}` }],
  }));
}

function buildSidebar(dirName: string, label: string, introId: string) {
  return [
    {
      type: 'category' as const,
      label,
      link: { type: 'doc' as const, id: introId },
      className: 'sidebar-category-hidden-header',
      collapsed: false,
      collapsible: false,
      items: buildSidebarCategories(dirName),
    },
  ];
}

const sidebars: SidebarsConfig = {
  cryptoWebSecSidebar: buildSidebar('crypto-web-security', '暗号・Web・NWセキュリティ', 'crypto-web-security/intro'),
  binarySecDevSidebar: buildSidebar('binary-sec-dev',       'バイナリ・開発・CTF',        'binary-sec-dev/intro'),
};

export default sidebars;
