import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  datastructureSidebar: [{ type: 'autogenerated', dirName: 'data-structure' }],
  algorithmSidebar: [{ type: 'autogenerated', dirName: 'algorithm' }],
  booksmSidebar: [{ type: 'autogenerated', dirName: 'books' }],


};

export default sidebars;
